MAINT: Deselect SVM sparse tests failing after sparse config change (#3041)
* MAINT: Deselect SVM sparse tests failing after sparse config change

csr_array (from #3029) does not support 1D slicing which
test_unsorted_indices and test_sparse_decision_function use.
NotImplementedError: We have not yet implemented 1D sparse slices.

Signed-off-by: yuejiaointel <yue.jiao@intel.com>

* Apply suggestion from @ethanglaser

---------

Signed-off-by: yuejiaointel <yue.jiao@intel.com>
Co-authored-by: ethanglaser <42726565+ethanglaser@users.noreply.github.com>